// Paste this entire block into the browser console while The Forge is open,
// OR have Antigravity run it as a one-time migration script to patch
// every exercise in EXERCISE_LIBRARY with why/breath/easier/harder fields.
// After running, these fields will be available to openForm() automatically.

const EXERCISE_UPDATES = {
  // ── CHEST ──────────────────────────────────────────────
  "chest-incline-press":   { why:"The incline angle targets the upper chest — the hardest part to develop and what gives the chest its full, rounded look from every angle.", breath:"Inhale on the way down, exhale as you press up.", easier:"Reduce the angle — sit more upright to shift load off the shoulder.", harder:"Pause 2 seconds at the bottom stretch before pressing." },
  "chest-floor-press":     { why:"The floor limits range and removes shoulder strain, letting you safely move heavier weight — ideal for building raw pressing strength.", breath:"Inhale as you lower, exhale on the press.", easier:"Use lighter dumbbells and focus on feeling the chest squeeze at the top.", harder:"3-second lowering phase on every rep." },
  "chest-fly-floor":       { why:"Flyes isolate the chest through a wide range of motion that pressing can't replicate — essential for building chest width and the mind-muscle connection.", breath:"Inhale as you open the arms, exhale as you squeeze back together.", easier:"Reduce the arc — don't go as wide until flexibility improves.", harder:"Pause 2 seconds at the widest point of the stretch." },
  "chest-closegrip-floor": { why:"Close-grip pressing shifts emphasis to the inner chest and triceps simultaneously — two birds with one move.", breath:"Inhale on the way down, exhale on the press.", easier:"Wider grip if wrists feel uncomfortable.", harder:"Add a slow 3-second lowering phase." },
  "chest-pushup-burnout":  { why:"High-rep burnout at the end of a chest session flushes blood into the muscle and increases total volume without adding joint stress.", breath:"Exhale on the push, inhale on the way down. Breathe rhythmically.", easier:"Drop to knees when form breaks down to extend the set.", harder:"Elevate feet on the couch to increase the load on the upper chest." },
  "chest-flat-bench":      { why:"Flat bench press is the most effective chest builder available — full range, heavy load, direct mid-chest stimulus.", breath:"Big inhale before lowering, exhale forcefully on the press.", easier:"Reduce weight and focus on feeling the chest rather than moving load.", harder:"Pause 1 second on the chest before pressing." },
  "chest-incline-bench":   { why:"Incline pressing fills out the upper chest — the area most people neglect and the one that makes the chest look complete from the front.", breath:"Inhale on the way down, exhale on the press.", easier:"Lower the bench angle closer to flat.", harder:"Slow 3-second descent on every rep." },
  "chest-decline-bench":   { why:"Decline targets the lower chest and sternal fibers — gives the chest a defined lower edge and works muscle fibers flat pressing misses.", breath:"Inhale as you lower, exhale as you press.", easier:"Reduce weight significantly — the angle makes it feel heavier.", harder:"Pause at the bottom for a full 2-second stretch." },
  "chest-fly-bench":       { why:"Bench flyes stretch the chest through a fuller range than floor flyes, maximizing the stretch stimulus that drives muscle growth.", breath:"Inhale as you open and lower, exhale as you squeeze back up.", easier:"Reduce the range of motion until shoulder flexibility improves.", harder:"Pause 2 seconds at the bottom of each rep." },
  "chest-pullover-bench":  { why:"Pullovers uniquely stretch the chest and lats simultaneously — expands the ribcage and works the serratus, giving the torso a wider look.", breath:"Inhale as you lower behind the head, exhale as you pull back over.", easier:"Reduce range — stop before any shoulder discomfort.", harder:"Add a 2-second pause at the fully stretched position." },
  "chest-deep-pushup":     { why:"Push-up handles allow a deeper stretch at the bottom than floor push-ups — that extra range is where most chest growth happens.", breath:"Inhale on the way down, exhale on the push.", easier:"Elevate hands slightly to reduce the depth.", harder:"Add a 3-second lowering phase or elevate feet." },
  "chest-archer-pushup":   { why:"Archer push-ups load one side at a time, building unilateral strength and fixing left-right imbalances most people don't know they have.", breath:"Inhale as you lower toward one side, exhale as you press back.", easier:"Keep more weight on both arms — don't extend the non-working arm as far.", harder:"Add a pause at the bottom on each side." },
  "chest-ring-pushup":     { why:"The instability of rings forces every chest stabilizer to fire simultaneously — harder than any fixed push-up and builds serious functional strength.", breath:"Inhale on the way down, exhale on the push.", easier:"Raise the rings higher to reduce the difficulty.", harder:"Turn rings out fully at the top and add a pause at the bottom." },
  "chest-ring-fly":        { why:"Ring flyes are one of the most advanced chest isolation moves available — the instability multiplies the difficulty and the muscle activation.", breath:"Inhale as you open, exhale as you pull back together.", easier:"Reduce the lean angle — less bodyweight = less load.", harder:"Add a 3-second hold at the open position." },

  // ── BACK ──────────────────────────────────────────────
  "back-bentover-row":     { why:"The bent-over row is the single best dumbbell back exercise — it loads the entire posterior chain and builds the thickness that makes a back look powerful.", breath:"Inhale before the pull, exhale as you row up.", easier:"Use lighter weight and focus on squeezing the shoulder blades at the top.", harder:"Pause 2 seconds at the top of each rep with a hard squeeze." },
  "back-singlearm-row":    { why:"Single-arm rows let you move more weight than any other dumbbell back exercise and correct left-right imbalances at the same time.", breath:"Exhale as you row up, inhale as you lower.", easier:"Use a lighter dumbbell and focus on the lat pulling, not the arm.", harder:"Add a 2-second hold at the top before lowering." },
  "back-pullover-couch":   { why:"Pullovers are one of the only exercises that directly stretch the lats under load — that stretched position is highly effective for lat development.", breath:"Inhale as you lower behind the head, exhale as you pull back.", easier:"Reduce the range — don't go as far behind the head.", harder:"Add a 2-second pause at full stretch." },
  "back-pull-apart":       { why:"Pull-aparts directly target the rear delts and upper back — muscles that prevent rounded shoulders and protect the rotator cuff long term.", breath:"Exhale as you pull apart, inhale as you return.", easier:"Use a lighter or longer band.", harder:"Slow the return to 3 seconds — resist the band." },
  "back-shrug":            { why:"Shrugs build the traps — the muscle that sits at the top of the back and neck and makes the upper body look thick and powerful from behind.", breath:"Inhale before the shrug, exhale at the top.", easier:"Use lighter dumbbells and focus on the peak contraction.", harder:"Hold 3 seconds at the top of each rep." },
  "back-rdl":              { why:"Romanian deadlifts build the lower back, glutes, and hamstrings simultaneously — the posterior chain foundation that transfers to every other lift.", breath:"Big inhale before hinging, exhale as you stand back up.", easier:"Reduce range of motion — hinge only as far as you can with a flat back.", harder:"Slow 4-second lowering phase." },
  "back-pullup":           { why:"Pull-ups are the king of back exercises — nothing builds lat width and upper back thickness like vertical pulling against your full bodyweight.", breath:"Exhale as you pull up, inhale as you lower.", easier:"Do negatives — jump to the top, lower as slowly as possible.", harder:"Add a pause at the top with chin over bar for 2 seconds." },
  "back-chinup":           { why:"Chin-ups emphasize the biceps more than pull-ups while still building the lats — a perfect bridge between a back and arm exercise.", breath:"Exhale on the pull, inhale on the descent.", easier:"Use a resistance band looped over the bar for assistance.", harder:"Add a weight belt or hold a dumbbell between your feet." },
  "back-wide-pullup":      { why:"Wide grip pull-ups maximize lat width by increasing the range of motion and reducing bicep involvement — pure lat builder.", breath:"Exhale as you pull, inhale as you lower.", easier:"Use a resistance band for assistance.", harder:"Slow 4-second descent on every rep." },
  "back-negative-pullup":  { why:"Negatives build pulling strength faster than any other method — you're stronger in the lowering phase, so you can train the movement before you can do a full rep.", breath:"Inhale at the top, exhale slowly as you lower.", easier:"Use a slightly faster descent — 3 seconds instead of 5.", harder:"Aim for a full 8-second descent." },
  "back-hanging-leg-raise": { why:"Hanging leg raises strengthen the core while also building grip and shoulder stability — a full chain movement disguised as an ab exercise.", breath:"Exhale as you raise the legs, inhale as you lower.", easier:"Bend the knees and do knee raises instead.", harder:"Add a pause at the top with legs parallel to the floor." },
  "back-trx-row":          { why:"TRX rows let you adjust the difficulty instantly by changing your body angle — and the instability recruits more stabilizers than any fixed row.", breath:"Exhale as you pull, inhale as you lower.", easier:"Walk feet back toward the anchor to make it less horizontal.", harder:"Walk feet forward so your body is more horizontal." },
  "back-trx-facepull":     { why:"Face pulls are one of the most important shoulder health exercises you can do — they balance out all the pressing and prevent rotator cuff injuries over time.", breath:"Exhale as you pull to your face, inhale as you return.", easier:"Lean back less — reduce the load.", harder:"Add a 3-second hold at the face with elbows high." },
  "back-ring-row":         { why:"Ring rows are highly scalable and the instability forces the entire back to stabilize — more muscle activation than a fixed bar row.", breath:"Exhale on the pull, inhale on the way down.", easier:"Walk feet back toward the anchor point.", harder:"Elevate feet on a chair to make it near-horizontal." },
  "back-banded-row":       { why:"Banded rows provide constant tension throughout the range of motion — unlike dumbbells, the resistance doesn't drop at the top.", breath:"Exhale as you row, inhale as you extend.", easier:"Use a lighter band or stand more upright.", harder:"Slow the return to 3 seconds." },
  "back-banded-pullapart": { why:"Heavy band pull-aparts build the posterior shoulder and upper back — directly counteracts the forward shoulder posture most people develop from sitting.", breath:"Exhale as you pull apart, inhale as you return.", easier:"Use a lighter band.", harder:"Slow the return to a full 4 seconds." },

  // ── SHOULDERS ──────────────────────────────────────────
  "sh-ohp":                { why:"The overhead press is the foundation of shoulder size — it loads all three delt heads and the triceps simultaneously with heavy compound stress.", breath:"Inhale before pressing, exhale forcefully at the top.", easier:"Seated position removes the need to stabilize the core — easier to focus on the delts.", harder:"Slow 3-second descent on every rep." },
  "sh-lateral":            { why:"Lateral raises are the only exercise that directly targets the side delt — the muscle responsible for shoulder width and that capped, athletic look.", breath:"Exhale as you raise, inhale as you lower.", easier:"Reduce weight significantly — this is a small muscle, 10–15 lb is plenty to start.", harder:"Add a 2-second pause at the top of each rep." },
  "sh-arnold":             { why:"The Arnold press works all three delt heads in one movement by combining a rotation with the press — more complete than a standard overhead press.", breath:"Inhale at the bottom, exhale as you rotate and press up.", easier:"Slow down the rotation to make it more controlled.", harder:"Add a 2-second pause at the top of each rep." },
  "sh-frontraise":         { why:"Front raises isolate the anterior deltoid — the front of the shoulder that contributes to the rounded, full shoulder look from the side.", breath:"Exhale as you raise, inhale as you lower.", easier:"Alternate arms to reduce fatigue.", harder:"Hold a 2-second pause at shoulder height." },
  "sh-reardelt-fly":       { why:"Rear delt flyes target the most neglected part of the shoulder — the posterior head. Training it prevents shoulder injuries and improves posture.", breath:"Exhale as you raise, inhale as you lower.", easier:"Reduce weight and increase reps — rear delts respond well to volume.", harder:"Pause 2 seconds at the top of each rep." },
  "sh-band-facepull":      { why:"Band face pulls are essential shoulder maintenance — they strengthen the external rotators and rear delts that protect the joint from pressing injuries.", breath:"Exhale as you pull to your face, inhale as you return.", easier:"Use a lighter band or stand closer to the anchor.", harder:"Add a 3-second hold with elbows high." },
  "sh-kb-press":           { why:"The kettlebell's offset center of mass forces more stabilizer activation than a dumbbell — builds shoulder stability and core strength simultaneously.", breath:"Inhale in the rack position, exhale as you press.", easier:"Use a lighter kettlebell and focus on keeping the wrist stacked over the elbow.", harder:"Add a 2-second pause at the top." },
  "sh-kb-getup":           { why:"The Turkish get-up is the ultimate shoulder stability exercise — it trains the shoulder through every plane of motion under load. One of the best movements in existence.", breath:"Breathe steadily and deliberately through each transition — never hold your breath.", easier:"Use no weight first — perfect the movement pattern before adding a kettlebell.", harder:"Add a longer pause at each position of the movement." },
  "sh-trx-ytw":            { why:"Y-T-W raises target the rotator cuff and scapular stabilizers — the small muscles that keep the shoulder joint healthy under heavy pressing loads.", breath:"Exhale as you raise into each position, inhale as you return.", easier:"Lean back less to reduce the load.", harder:"Hold each position for 2 seconds." },
  "sh-seated-bench-press": { why:"Seated shoulder press on a bench provides back support that lets you focus entirely on the delts — useful when going heavy.", breath:"Inhale before pressing, exhale on the way up.", easier:"Reduce weight and focus on full range of motion.", harder:"Slow 3-second descent." },

  // ── TRICEPS ────────────────────────────────────────────
  "tri-dip-chair":         { why:"Dips load the tricep through its full range of motion — more effective than any isolation exercise and can be progressively loaded by adding weight.", breath:"Inhale on the way down, exhale as you press up.", easier:"Bend knees and bring feet closer to the chair.", harder:"Rest a dumbbell on your lap or slow the descent to 4 seconds." },
  "tri-overhead-ext":      { why:"Overhead extensions specifically target the long head of the tricep — the largest portion and the one that gives the arm its mass when viewed from behind.", breath:"Inhale as you lower behind the head, exhale as you extend.", easier:"Use a lighter dumbbell and reduce the range of motion.", harder:"Slow 3-second lowering phase." },
  "tri-skull-crusher":     { why:"Skull crushers isolate the tricep completely — all three heads work together through the full range with no assistance from other muscles.", breath:"Inhale as you lower, exhale as you extend.", easier:"Reduce weight and stop before any elbow discomfort.", harder:"Add a 2-second pause near the ears before extending." },
  "tri-kickback":          { why:"Kickbacks force the tricep to contract at full extension — a unique position that maximizes the squeeze and builds the horseshoe shape.", breath:"Exhale as you extend back, inhale as you return.", easier:"Use a lighter dumbbell — form breaks down fast with too much weight.", harder:"Hold the fully extended position for 2 seconds." },
  "tri-closegrip-floor":   { why:"Close-grip pressing hits the triceps with a compound movement — you can go heavier than any isolation exercise which means more growth stimulus.", breath:"Inhale on the way down, exhale on the press.", easier:"Widen grip slightly if wrists are uncomfortable.", harder:"Slow 3-second descent." },
  "tri-dip-bars":          { why:"Parallel bar dips are the gold standard tricep exercise — full depth, heavy load, and the ability to add weight makes them endlessly progressive.", breath:"Inhale on the way down, exhale as you press up.", easier:"Use a resistance band looped over the bars for assistance.", harder:"Add a weight belt or hold a dumbbell between your feet." },
  "tri-dip-weighted":      { why:"Weighted dips take parallel bar dips to the next level — adding load forces the triceps to adapt beyond bodyweight and drives serious size gains.", breath:"Inhale on the descent, exhale on the press.", easier:"Reduce the added weight or return to bodyweight.", harder:"Increase the load incrementally — even 5 lb per week adds up fast." },
  "tri-ring-dip":          { why:"Ring dips are significantly harder than bar dips — the instability forces every tricep stabilizer to fire and builds functional pressing strength.", breath:"Inhale on the way down, exhale as you press up.", easier:"Keep rings lower so feet can touch down if needed.", harder:"Add a 3-second lowering phase." },
  "tri-ring-ext":          { why:"Ring tricep extensions load the long head through a deep stretch position that most exercises can't reach — highly effective for adding mass to the back of the arm.", breath:"Inhale as you lower toward the rings, exhale as you extend.", easier:"Stand more upright to reduce the load.", harder:"Walk feet forward so your body is more horizontal." },
  "tri-diamond-pushup":    { why:"Diamond push-ups shift the load almost entirely to the triceps — a simple bodyweight finisher that creates a serious burn without any equipment.", breath:"Inhale on the way down, exhale on the push.", easier:"Elevate hands on a surface to reduce the load.", harder:"Elevate feet to increase difficulty." },

  // ── BICEPS ────────────────────────────────────────────
  "bi-curl":               { why:"The standard curl is the foundation of bicep training — simple, proven, and effective when done strictly with a full range of motion.", breath:"Exhale as you curl up, inhale as you lower.", easier:"Use lighter weight and focus on the squeeze at the top.", harder:"Slow 3-second lowering phase — the negative builds as much muscle as the lift." },
  "bi-hammer":             { why:"Hammer curls target the brachialis — a muscle that sits under the bicep and pushes it up when developed, making the arm look significantly thicker.", breath:"Exhale as you curl, inhale as you lower.", easier:"Alternate arms to reduce fatigue.", harder:"Slow 3-second descent on every rep." },
  "bi-concentration":      { why:"Concentration curls eliminate all momentum and force the bicep to do 100% of the work — the best exercise for developing the peak of the bicep.", breath:"Exhale as you curl up, inhale as you lower.", easier:"Use a lighter dumbbell and focus purely on the peak contraction.", harder:"Hold the contracted position at the top for 2 seconds." },
  "bi-incline-curl":       { why:"Incline curls stretch the bicep at the start position — that stretched stimulus is one of the strongest signals for muscle growth.", breath:"Exhale as you curl, inhale as you lower fully.", easier:"Reduce the incline angle.", harder:"Hold the bottom stretched position for 2 seconds before curling." },
  "bi-zottman":            { why:"Zottman curls train both the bicep and forearm extensors in one movement — the rotation between supinated and pronated grip doubles the stimulus.", breath:"Exhale on the way up, inhale slowly on the pronated descent.", easier:"Slow the rotation down if wrists feel awkward.", harder:"Slow the descent to 4 seconds." },
  "bi-chinup-bar":         { why:"Chin-ups are the most effective bicep exercise that exists — you're pulling your entire bodyweight through a full range of motion.", breath:"Exhale as you pull up, inhale as you lower.", easier:"Use a resistance band for assistance.", harder:"Add weight via a belt or slow the descent to 5 seconds." },
  "bi-band-curl":          { why:"Banded curls provide constant tension — unlike dumbbells the load doesn't drop at the top, keeping the muscle under stress through the full rep.", breath:"Exhale as you curl, inhale as you lower.", easier:"Use a lighter band.", harder:"Slow the lowering phase to 3 seconds." },
  "bi-band-hammer":        { why:"Banded hammer curls target the brachialis with constant tension — great for adding thickness to the arm without needing heavy weights.", breath:"Exhale on the curl, inhale on the descent.", easier:"Use a lighter band.", harder:"Slow 3-second descent." },
  "bi-trx-curl":           { why:"TRX curls force the core to stabilize while the biceps work — trains functional arm strength and the unstable surface increases muscle activation.", breath:"Exhale as you curl toward your temples, inhale as you lower.", easier:"Walk feet back toward the anchor to reduce the load.", harder:"Walk feet forward — more horizontal = more load." },

  // ── LEGS ──────────────────────────────────────────────
  "leg-goblet":            { why:"The goblet squat is the best teaching squat — the counterbalance of the weight in front naturally pulls you into perfect form.", breath:"Big inhale before descending, exhale as you drive up.", easier:"Reduce depth — squat only as low as you can with a flat back.", harder:"Add a 3-second pause at the bottom position." },
  "leg-bulgarian":         { why:"Bulgarian split squats are one of the most effective leg exercises available — they load the quads and glutes unilaterally and expose strength imbalances.", breath:"Inhale as you lower, exhale as you drive up.", easier:"Start with bodyweight only — this exercise is harder than it looks.", harder:"Add dumbbells and slow the descent to 3 seconds." },
  "leg-rdl":               { why:"Romanian deadlifts build the hamstrings and glutes through a loaded stretch — the posterior chain development that directly improves every other lower body lift.", breath:"Big inhale before hinging, exhale as you stand.", easier:"Reduce range — hinge only as far as you can with a flat back.", harder:"Slow 4-second descent." },
  "leg-reverse-lunge":     { why:"Reverse lunges are easier on the knee than forward lunges and train single-leg balance — essential for functional leg strength.", breath:"Inhale as you step back, exhale as you return.", easier:"Reduce the step length and hold a wall for balance if needed.", harder:"Add dumbbells or slow the descent." },
  "leg-step-up":           { why:"Step-ups isolate each leg completely and eliminate the ability to compensate with the other leg — true unilateral strength builder.", breath:"Exhale as you step up, inhale as you step down.", easier:"Use a lower surface.", harder:"Add dumbbells and slow the step-down." },
  "leg-calf-raise":        { why:"Calves are often undertrained because people rush them — slow, heavy calf raises with a pause at the top are the key to development.", breath:"Exhale as you rise, inhale as you lower.", easier:"Use bodyweight only and focus on the pause at the top.", harder:"Stand on a step for greater range and add dumbbells." },
  "leg-kb-swing":          { why:"KB swings build explosive hip power and condition the entire posterior chain in one movement — one of the most efficient exercises that exists.", breath:"Sharp exhale at the top of the swing, inhale on the way down.", easier:"Use a lighter kettlebell and focus on the hip snap.", harder:"Increase reps to 20 or use a heavier kettlebell." },
  "leg-kb-goblet":         { why:"KB goblet squats allow you to squat deeper than a dumbbell version — the shape of the kettlebell sits more naturally at the chest.", breath:"Inhale before descending, exhale driving up.", easier:"Reduce depth.", harder:"Pause 3 seconds at the bottom." },
  "leg-kb-sldl":           { why:"Single-leg deadlifts build balance and hamstring strength simultaneously — they expose and correct the left-right strength imbalances most people have.", breath:"Inhale before hinging, exhale as you stand.", easier:"Touch the non-working foot lightly to the floor for balance.", harder:"Add a pause at the fully hinged position." },
  "leg-box-jump":          { why:"Box jumps develop explosive power — the fast-twitch muscle fibers recruited during jumping also contribute to strength and size when combined with heavy lifting.", breath:"Sharp exhale as you explode up, inhale on landing.", easier:"Use a lower box or do a squat jump to the floor first.", harder:"Use a higher box or add a 3-second pause squat before each jump." },
  "leg-box-stepup":        { why:"Box step-ups with a knee drive add a hip flexor challenge to the standard step-up — more functional and burns more calories.", breath:"Exhale as you drive the knee up, inhale as you step down.", easier:"Remove the knee drive and just step up and down.", harder:"Add dumbbells." },
  "leg-depth-drop":        { why:"Depth drops train the reactive strength system — your nervous system learns to absorb force quickly, which protects joints and improves athletic performance.", breath:"Inhale before stepping off, sharp exhale as you absorb the landing.", easier:"Use a lower box.", harder:"Add a jump immediately after absorbing the landing." },
  "leg-banded-squat":      { why:"The band adds accommodating resistance — hardest at the top where regular squats are easiest, forcing the glutes to fire hard through lockout.", breath:"Inhale before squatting, exhale as you drive up.", easier:"Use a lighter band.", harder:"Add a 2-second pause at the bottom." },
  "leg-banded-rdl":        { why:"Banded RDLs keep constant tension on the hamstrings through the full range — more effective than dumbbell RDLs for hamstring isolation.", breath:"Inhale before hinging, exhale as you stand.", easier:"Use a lighter band.", harder:"Slow 4-second descent." },
  "leg-banded-lunge":      { why:"Banded lunges add front-foot resistance that challenges the quads at the top of the movement where bodyweight lunges provide no stimulus.", breath:"Inhale as you lunge back, exhale as you return.", easier:"Use a lighter band.", harder:"Slow the descent to 3 seconds." },
  "leg-squat-slam":        { why:"Squat slams combine leg power with explosive upper body work — builds conditioning, coordination and burns significantly more calories than isolation work.", breath:"Inhale on the squat, sharp exhale as you slam.", easier:"Use a lighter ball and focus on the movement pattern.", harder:"Increase reps or use a heavier ball." },

  // ── CORE ──────────────────────────────────────────────
  "core-abwheel":          { why:"The ab wheel rollout is the hardest and most effective core exercise available at home — it trains anti-extension, the core's primary function.", breath:"Inhale before rolling out, exhale as you pull back.", easier:"Reduce range — only go as far as you can while keeping your back flat.", harder:"Roll out further or progress to standing rollouts." },
  "core-hanging-knee":     { why:"Hanging knee raises build core strength while also developing grip and shoulder stability — a full chain exercise masquerading as an ab move.", breath:"Exhale as you raise the knees, inhale as you lower.", easier:"Use a smaller range of motion.", harder:"Slow the lowering phase to 3 seconds." },
  "core-hanging-leg":      { why:"Straight leg raises are significantly harder than knee raises and directly target the lower abs — the area most people struggle to develop.", breath:"Exhale as you raise, inhale as you lower.", easier:"Bend the knees slightly.", harder:"Add a pause at the top with legs parallel to the floor." },
  "core-ring-plank":       { why:"Ring planks are exponentially harder than floor planks — the rings try to spread and your entire core fires at maximum to resist it.", breath:"Breathe slow and steady throughout the hold.", easier:"Keep rings close to the floor.", harder:"Add small forward and backward rocks." },
  "core-bodysaw":          { why:"Body saws train anti-extension — the core's real job is resisting movement, not creating it. This movement directly builds functional core stability.", breath:"Exhale as you push forward, inhale as you pull back.", easier:"Reduce the range of the saw.", harder:"Add a 2-second pause at full extension." },

  // ── WARMUP ────────────────────────────────────────────
  "warmup-rope":           { why:"Jump rope raises heart rate, warms up the ankles and wrists, and improves coordination — far better than static stretching before a workout.", breath:"Breathe naturally and rhythmically throughout.", easier:"Slow the pace — just focus on consistent rhythm.", harder:"Add double-unders or increase the duration." },
  "warmup-mobility":       { why:"Dynamic mobility drills lubricate the joints and activate the muscles you're about to train — reduces injury risk and improves performance.", breath:"Breathe slowly and deliberately through each movement.", easier:"Reduce the range of motion on each drill.", harder:"Add more rotations and increase the speed of each movement." }
};
